{
 "title": "K8s: Requests/Limits overview",
 "tags": [
  "kubernetes",
  "requests",
  "limits"
 ],
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_resource_limits, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (memory bytes)",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container) (kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Limits (memory bytes)",
   "type": "table",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container) (kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Usage/Limit ratio",
   "type": "table",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container) (container_memory_working_set_bytes{container!=\"\", image!=\"\", namespace=~\"$namespace\"}) / sum by (namespace,pod,container) (kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}