apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prom-stack-prometheus.observability.svc:9090
        isDefault: false
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc:3100
        editable: true
